let token = localStorage.getItem('eims_token');
let role = localStorage.getItem('eims_role');
const $ = id => document.getElementById(id);
async function api(path, options={}) { options.headers = {...(options.headers||{}), ...(token?{Authorization:`Bearer ${token}`}:{})}; const r=await fetch(path,options); if(!r.ok){let d={};try{d=await r.json()}catch{};throw new Error(d.detail||`HTTP ${r.status}`)} return r.json(); }
function setLoggedIn(){ $('login-card').classList.toggle('hidden',!!token); $('app').classList.toggle('hidden',!token); $('logout').classList.toggle('hidden',!token); $('add-btn').classList.toggle('hidden',!['ADMIN','MANAGER'].includes(role)); if(token) refresh(); }
$('login-form').onsubmit=async e=>{e.preventDefault();$('login-error').textContent='';try{const d=await api('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:$('username').value,password:$('password').value})});token=d.access_token;role=d.role;localStorage.setItem('eims_token',token);localStorage.setItem('eims_role',role);setLoggedIn()}catch(err){$('login-error').textContent=err.message)}};
$('logout').onclick=()=>{token=null;role=null;localStorage.clear();setLoggedIn()}; $('refresh').onclick=refresh; $('search').oninput=refresh; $('status').onchange=refresh;
$('add-btn').onclick=()=>{$('form-card').classList.remove('hidden')}; $('cancel-add').onclick=()=>{$('form-card').classList.add('hidden')};
$('component-form').onsubmit=async e=>{e.preventDefault();$('form-error').textContent='';const data=Object.fromEntries(new FormData(e.target).entries());data.quantity=Number(data.quantity);data.unit_price=Number(data.unit_price);data.reorder_level=Number(data.reorder_level);try{await api('/api/inventory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});e.target.reset();$('form-card').classList.add('hidden');refresh()}catch(err){$('form-error').textContent=err.message)}};
async function refresh(){if(!token)return;try{const q=new URLSearchParams();if($('search').value)q.set('search',$('search').value);if($('status').value)q.set('status',$('status').value);const [items,dash]=await Promise.all([api('/api/inventory?'+q),api('/api/dashboard')]);$('stats').innerHTML=`<div class="stat">Total components<b>${dash.total_components}</b></div><div class="stat">Stock value<b>₹${dash.total_stock_value.toFixed(2)}</b></div><div class="stat">Low stock<b>${dash.low_stock_count}</b></div>`;$('inventory').innerHTML=items.map(c=>{const s=c.quantity===0?'out-of-stock':c.quantity<=c.reorder_level?'low-stock':'in-stock';const action=['ADMIN','MANAGER'].includes(role)?`<button onclick="removeItem(${c.id})">Delete</button>`:'Read only';return `<tr><td>${c.sku}</td><td>${c.name}</td><td>${c.category}</td><td>${c.quantity}</td><td>₹${c.unit_price.toFixed(2)}</td><td>${c.supplier}</td><td>${c.reorder_level}</td><td class="status">${s}</td><td>${action}</td></tr>`}).join('')}catch(err){if(err.message.includes('401')){localStorage.clear();token=null;setLoggedIn()}}}
window.removeItem=async id=>{if(!confirm('Delete this component?'))return;try{await api('/api/inventory/'+id,{method:'DELETE'});refresh()}catch(err){alert(err.message)}};
setLoggedIn();
